services:
  server:
    build:
      dockerfile: Dockerfile # for tts-1-hd support via xtts_v2, ~4GB VRAM required, ~10GB
      #dockerfile: Dockerfile.min # piper for all models, no gpu/nvidia required, ~1GB
    image: ghcr.io/matatonic/openedai-speech
    #image: ghcr.io/matatonic/openedai-speech-min
    env_file: speech.env
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    #restart: unless-stopped # install as a service
    # Below can be removed if not using GPU
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
