version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.min
      #dockerfile: Dockerfile # for tts-1-hd support via xtts_v2
    stdin_open: true
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              #device_ids: ['0', '1']
              capabilities: [gpu]
    ports:
      - "8000:8000"
