version: "3.3"
services:
  server:
    build:
      context: .
      #dockerfile: Dockerfile.min # piper for all models, no gpu/nvidia required, ~900MB
      dockerfile: Dockerfile # for tts-1-hd support via xtts_v2, ~4GB VRAM required, 13GB
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
#    volumes:
#      - .:/app/
    # Below can be removed if not using GPU
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
